name: Manu
favicon: null
layout_spectrum: 0.0189
typography_spectrum: 0.1594725342001766
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#242727'
    - '#7fb759'
    - '#000000'
    - '#4e4e4e'
  brandStrength: 0.5
  lightness: 0.3866776917129755
  saturation: 0.4700669785961509
  rhythmicContrast: 0.4689433730673045
purpose: []
